#!/usr/bin/env bash

set -e

# shellcheck source=docker/load_backups_secrets
source load_backups_secrets

echo "--------------------------------------------"
echo "$(date): Starting ${UPLOADS_PATH:?must be set} backup..."

aws s3 sync \
  --acl private \
  --storage-class "${AWS_S3_STORAGE_CLASS:?must be set}" \
  "${UPLOADS_PATH}" "s3://${AWS_S3_BUCKET:?must be set}/uploads"

echo "$(date): ${UPLOADS_PATH} backup succeeded"
