#!/usr/bin/env bash

set -e

# shellcheck source=docker/load_backups_secrets
source load_backups_secrets

aws s3 sync \
  --acl private \
  --storage-class "${AWS_S3_STORAGE_CLASS:?must be set}" \
  "${UPLOADS_PATH:?must be set}" "s3://${AWS_S3_BUCKET:?must be set}/uploads"

echo "${UPLOADS_PATH} backup succeeded at $(date)"
