#!/usr/bin/env bash

set -e
[ -z "$DEBUG" ] || set -x

main() {
  is_repository || clone_repository
  reset_to_remote_branch
  deploy_docker_stack
  [ -z "$UPDATE_APP_EVERY_N_SECONDS" ] || update_app_continuously
}

reset_to_remote_branch() {
  git fetch origin "${GIT_BRANCH:?must be set}"
  git reset --hard origin/"$GIT_BRANCH"
}

is_repository() {
  git remote -v
}

clone_repository() {
  git clone "${GIT_REPOSITORY:?must be set}" /app
}

deploy_docker_stack() {
  make deploy-docker-stack
}

update_app_continuously() {
  echo "Updating App every ${UPDATE_APP_EVERY_N_SECONDS:?must be set} seconds..."
  while sleep "$UPDATE_APP_EVERY_N_SECONDS"
  do
    make update-app-service
  done
}

main
