#!/usr/bin/env bash

set -e
set -o pipefail

# shellcheck source=docker/load_backups_secrets
source load_backups_secrets

read -rp "
Are you sure that you want to delete everything in database: ${PGDATABASE:?must be set} ? (y|n) " -n 1
echo
if ! [[ $REPLY =~ ^[Yy]$ ]]
then
  echo "ABORT - $PGDATABASE database was not cleaned"
  exit 0
fi

echo "
Deleting everything in database: $PGDATABASE ..."

echo "
/* https://dba.stackexchange.com/questions/11893/force-drop-db-while-others-may-be-connected */
/* Make sure no one can connect to this database */
UPDATE pg_database SET datallowconn = 'false' WHERE datname = '$PGDATABASE';
/* Force disconnection of all clients connected to this database */
SELECT pg_terminate_backend(pid)
FROM pg_stat_activity
WHERE datname = '$PGDATABASE';
/* Drop the database */
DROP DATABASE $PGDATABASE;" \
| psql postgres

createdb "$PGDATABASE"

echo "
SUCCESS! $PGDATABASE database was cleaned"
