#!/usr/bin/env bash

set -e
[ -z "$DEBUG" ] || set -x

main() {
  is_repository || clone_repository
  reset_to_remote_branch
  deploy_docker_stack
}

reset_to_remote_branch() {
  git fetch origin "${GIT_BRANCH:?must be set}"
  git reset --hard origin/"$GIT_BRANCH"
}

is_repository() {
  git remote --verbose
}

clone_repository() {
  git clone "${GIT_REPOSITORY:?must be set}" /app
}

deploy_docker_stack() {
  make --makefile "${MAKEFILE:?must be set}" deploy-docker-stack
}

main
