FROM thechangelog/changelog.com

ENV MIX_ENV prod

EXPOSE 4000
HEALTHCHECK --start-period=30s --interval=30s --timeout=30s --retries=3 \
  CMD curl --fail --silent http://127.0.0.1:4000 || exit 1

COPY ./config /app/config
