# Test image: runs mix test with app source compiled for test
ARG RUNTIME_IMAGE

FROM ${RUNTIME_IMAGE}

ENV MIX_ENV=test
WORKDIR /app

COPY config/ config/
COPY lib/ lib/
COPY priv/repo/ priv/repo/
COPY test/ test/
COPY mix.exs mix.lock ./

RUN mix deps.get --only test \
    && mix deps.compile \
    && mix compile

CMD ["mix", "test"]
