FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update \
    && apt-get install -y ca-certificates \
    && rm -fr /var/lib/apt/lists

# https://github.com/fastly/cli/releases
# wget https://github.com/fastly/cli/releases/download/v0.16.1/fastly_v0.16.1_linux-amd64.tar.gz
ADD fastly_v0.16.1_linux-amd64.tar.gz /usr/local/bin
RUN fastly version
RUN echo 'eval "$(fastly --completion-script-bash)"' > /etc/profile.d/fastly.sh
