FROM thechangelog/legacy_assets AS legacy_assets
FROM thechangelog/runtime:2020-12-14T20.59.58Z

RUN mkdir /app
COPY . /app
WORKDIR /app

COPY --from=legacy_assets /var/www/wp-content /app/priv/wp-content

ENV MIX_ENV=prod
ENV TERM=xterm

EXPOSE 4000

CMD mix do ecto.create, ecto.migrate, phx.server
