FROM thechangelog/runtime:2019-05-24T21.10.15Z

RUN mkdir /app
COPY . /app
WORKDIR /app

ENV MIX_ENV=prod
ENV TERM=xterm

EXPOSE 4000

CMD make report-deploy ; mix do ecto.create, ecto.migrate, phx.server
