# https://hub.docker.com/_/nginx?tab=tags
# https://nginx.org/en/CHANGES
FROM nginx:1.17

COPY ./tmp/ten-curl.html /usr/share/nginx/html/index.html
COPY ./tmp/ten-monolith.html /usr/share/nginx/html/monolith.html
COPY ./assets/static/favicon.ico /usr/share/nginx/html/favicon.ico
RUN mkdir /usr/share/nginx/html/live && touch /usr/share/nginx/html/live/status
