#!/usr/bin/env bash

set -e
set -o pipefail

# shellcheck source=docker/load_backups_secrets
source load_backups_secrets

LAST_DB_BACKUP=$(s3_backups | sort --reverse | awk '/\.gz$/ { print $5 }' | head -n 1)

aws s3 cp "s3://${AWS_S3_BUCKET:?must be set}/$LAST_DB_BACKUP" .
