#!/usr/bin/env bash

if [ -r /run/secrets/BACKUPS_AWS_ACCESS_KEY ]
then
  AWS_ACCESS_KEY_ID="$(cat /run/secrets/BACKUPS_AWS_ACCESS_KEY)"
  export AWS_ACCESS_KEY_ID
fi

if [ -r /run/secrets/BACKUPS_AWS_SECRET_KEY ]
then
  AWS_SECRET_ACCESS_KEY="$(cat /run/secrets/BACKUPS_AWS_SECRET_KEY)"
  export AWS_SECRET_ACCESS_KEY
fi

if [ -r /run/secrets/DB_PASSWORD ]
then
  PGPASSWORD="$(cat /run/secrets/DB_PASSWORD)"
  export PGPASSWORD
fi
