#!/usr/bin/env bash

set -e

# shellcheck source=docker/load_backups_secrets
source load_backups_secrets

echo "--------------------------------------------"
echo "$(date): Starting ${UPLOADS_PATH:?must be set} restore..."

aws s3 sync \
  "s3://${AWS_S3_BUCKET:?must be set}/uploads" "${UPLOADS_PATH}" 

echo "
$(date): ${UPLOADS_PATH} restored from s3://${AWS_S3_BUCKET}/uploads successfully"
