#!/usr/bin/env bash

set -e
set -o pipefail

# shellcheck source=docker/load_backups_secrets
source load_backups_secrets

echo "
Which backup to restore database ${PGDATABASE:?must be set} from?"
select DB_BACKUP in $(s3_backups | sort --reverse | awk '/\.gz$/ { print $5 }' | head -n 10)
do
  export DB_BACKUP
  break
done

read -rp "
Do you want to restore $PGDATABASE database from $DB_BACKUP backup? (y|n) " -n 1
echo
if ! [[ $REPLY =~ ^[Yy]$ ]]
then
  echo "ABORT - $PGDATABASE was not restored from backup"
  exit 0
fi

echo "
Restoring $PGDATABASE database from $DB_BACKUP ..."

aws s3 cp "s3://${AWS_S3_BUCKET:?must be set}/$DB_BACKUP" - \
| gunzip --stdout \
| psql

echo "
SUCCESS! $PGDATABASE database was restored from $DB_BACKUP"
