#!/usr/bin/env bash

if [ -r /run/secrets/BACKUPS_AWS_ACCESS_KEY ]
then
  AWS_ACCESS_KEY="$(cat /run/secrets/BACKUPS_AWS_ACCESS_KEY)"
fi

if [ -r /run/secrets/BACKUPS_AWS_SECRET_KEY ]
then
  AWS_SECRET_KEY="$(cat /run/secrets/BACKUPS_AWS_SECRET_KEY)"
fi

if [ -r /run/secrets/DB_PASSWORD ]
then
  PGPASSWORD="$(cat /run/secrets/DB_PASSWORD)"
  export PGPASSWORD
fi

echo "
Select backup to restore ${PGDATABASE:?must be set} db from:"
select DB_BACKUP in $(db_backups_s3 | awk '{ print $4 }' | head -n 10)
do
  export DB_BACKUP
  break
done

read -rp "
Do you want to restore $PGDATABASE db from $DB_BACKUP ? (y|n) " -n 1
echo
if ! [[ $REPLY =~ ^[Yy]$ ]]
then
  echo "ABORT - $PGDATABASE was not restored from backup"
  exit 0
fi

echo "
Restoring $PGDATABASE db from $DB_BACKUP ..."

s3cmd \
  --ssl --check-certificate --check-hostname --stop-on-error \
  --region="${AWS_REGION:?must be set}"  \
  --access_key="${AWS_ACCESS_KEY:?must be set}" \
  --secret_key="${AWS_SECRET_KEY:?must be set}" \
  get "$DB_BACKUP" - \
| gunzip --stdout \
| psql

echo "
SUCCESS! $PGDATABASE db was restored from $DB_BACKUP"
