#!/usr/bin/env bash

set -e

# shellcheck source=docker/load_db_restore_secrets
source load_db_restore_secrets

aws s3 cp \
  --acl private \
  --storage-class "${AWS_S3_STORAGE_CLASS:?must be set}" \
  - "s3://${AWS_S3_BUCKET:?must be set}/${AWS_S3_DEST_FILE_PATH:?must be set}"
