#!/usr/bin/env bash
# Shared helpers for team:* tasks. Sourced by tasks, never run directly — the
# leading underscore keeps mise from registering this file as a task.
#
#   source "${MISE_PROJECT_ROOT}/mise-tasks/team/_lib.sh"
#   require_env NEON_PROJECT_ID DB_PROD_USERNAME

# require_env VAR [VAR...]
# Exit with a fix-it message if any named variable is unset or empty.
# team:* tasks read config from mise's [env] and secrets from 1Password via
# fnox-env; a missing value almost always means secrets aren't loaded.
require_env() {
  local var missing=()
  for var in "$@"
  do
    [ -n "${!var:-}" ] || missing+=("${var}")
  done
  [ "${#missing[@]}" -eq 0 ] && return 0

  {
    echo ""
    echo "❌ Not set: ${missing[*]}"
    echo ""
    echo "   team:* tasks read config from mise's [env] and secrets from"
    echo "   1Password via fnox-env. A missing value usually means secrets"
    echo "   aren't loaded in this shell. To fix, run:"
    echo ""
    echo "     mise team:secrets:load"
    echo ""
    echo "   (it signs you in to 1Password if needed). Then re-run this task."
    echo "   See CONTRIBUTING.md → \"How do I configure secrets\"."
    echo ""
  } >&2
  exit 1
}

# require_env_file FILE PRODUCED_BY
# Source a generated env file, or exit with a fix-it message naming the task
# that produces it (e.g. PROD_IMAGE lives in tmp/mise-prod-image.env).
require_env_file() {
  local file="$1" produced_by="$2"
  if [ ! -f "${file}" ]
  then
    {
      echo ""
      echo "❌ Missing ${file}"
      echo ""
      echo "   It is generated by: ${produced_by}"
      echo "   Run that first, then re-run this task."
      echo ""
    } >&2
    exit 1
  fi
  # shellcheck disable=SC1090
  source "${file}"
}
