{
 "title": "PromEx - App - 2020.12.28",
 "description": "All the data that is presented here is captured by the PromEx Application plugin (https://github.com/akoutmos/prom_ex/blob/master/lib/prom_ex/plugins/application.ex)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(changelog_prom_ex_prom_ex_status_info, kubernetes_namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Application Uptime",
   "type": "stat",
   "description": "The amount of time that the application has been running.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "changelog_prom_ex_application_uptime_milliseconds_count{kubernetes_namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Dependency Information",
   "type": "table",
   "description": "The data is populated by the PromEx Application plugin and provides information regarding your application's dependencies.",
   "gridPos": { "h": 35, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "changelog_prom_ex_application_dependency_info{kubernetes_namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Application Name",
   "type": "stat",
   "description": "The name of the primary application that is running.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "changelog_prom_ex_application_primary_info{kubernetes_namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Application Git SHA",
   "type": "stat",
   "description": "The Git SHA of the application.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "changelog_prom_ex_application_git_sha_info{kubernetes_namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Application Version",
   "type": "stat",
   "description": "The version of the primary application that is running.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "changelog_prom_ex_application_primary_info{kubernetes_namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Application Modules Loaded",
   "type": "stat",
   "description": "The number of modules loaded by the primary application that is running.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "changelog_prom_ex_application_primary_info{kubernetes_namespace=\"$namespace\"}"
    }
   ]
  }
 ]
}