{
 "title": "PromEx - Ecto",
 "description": "All the data that is presented here is captured by the PromEx Ecto plugin (https://github.com/akoutmos/prom_ex/blob/master/lib/prom_ex/plugins/ecto.ex)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(changelog_prom_ex_prom_ex_status_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Host",
   "type": "stat",
   "description": "The host of the database that the Repo is connected to.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "changelog_prom_ex_ecto_repo_init_status_info{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Pool Size",
   "type": "stat",
   "description": "The pool size that the repo was initialized with.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "changelog_prom_ex_ecto_repo_init_pool_size{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Longest Connection Queue Time",
   "type": "gauge",
   "description": "The time spent waiting to check out a database connection.",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(irate(changelog_prom_ex_ecto_repo_query_queue_time_milliseconds_sum{namespace=\"$namespace\"}[$__interval])) by(app) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Longest Connection Decode Time",
   "type": "gauge",
   "description": "The time spent waiting to check out a database connection.",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(irate(changelog_prom_ex_ecto_repo_query_decode_time_milliseconds_sum{namespace=\"$namespace\"}[$__interval])) by(app) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Longest Execution Time",
   "type": "gauge",
   "description": "The time spent waiting to check out a database connection.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(irate(changelog_prom_ex_ecto_repo_query_execution_time_milliseconds_sum{namespace=\"$namespace\"}[$__interval])) by(app, command) > 0",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Name",
   "type": "stat",
   "description": "The host of the database that the Repo is connected to.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "changelog_prom_ex_ecto_repo_init_status_info{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Timeout",
   "type": "stat",
   "description": "The timeout duration that the Repo was initialized with.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "changelog_prom_ex_ecto_repo_init_timeout_duration{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Query Execution Time",
   "type": "graph",
   "description": "The average request time per path per status code per HTTP method.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms", "label": "Response Time" }
   ],
   "targets": [
    {
     "expr": "sum(irate(changelog_prom_ex_ecto_repo_query_execution_time_milliseconds_sum{namespace=\"$namespace\"}[$__interval])) by(command, source)",
     "legendFormat": "{{ command }} {{source }}"
    }
   ]
  },
  {
   "title": "Operations Per Source",
   "type": "graph",
   "description": "The average response size per path per status code per HTTP method.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "locale", "label": "Source Operations" }
   ],
   "targets": [
    {
     "expr": "sum(increase(changelog_prom_ex_ecto_repo_query_execution_time_milliseconds_count{namespace=\"$namespace\"}[$__interval])) by(source)",
     "legendFormat": "{{ source }}"
    }
   ]
  },
  {
   "title": "Operations Per Command",
   "type": "graph",
   "description": "The average response size per path per status code per HTTP method.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "locale", "label": "Source Operations" }
   ],
   "targets": [
    {
     "expr": "sum(increase(changelog_prom_ex_ecto_repo_query_execution_time_milliseconds_count{namespace=\"$namespace\"}[$__interval])) by(command)",
     "legendFormat": "{{ source }}"
    }
   ]
  },
  {
   "title": "Heatmaps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Execution Time",
     "type": "heatmap",
     "description": "A heatmap showing the request time spread across all Repo query executions (regardless of query type).",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sum(irate(changelog_prom_ex_ecto_repo_query_execution_time_milliseconds_bucket{namespace=\"$namespace\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Results Returned",
     "type": "heatmap",
     "description": "A heatmap showing the number of results returned from the database (summed up across all operations and sources).",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "sum(irate(changelog_prom_ex_ecto_repo_query_results_returned_bucket{namespace=\"$namespace\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  }
 ]
}