{
 "title": "PromEx - Erlang",
 "description": "All the data that is presented here is captured by the PromEx BEAM plugin (https://github.com/akoutmos/prom_ex/blob/master/lib/prom_ex/plugins/beam.ex)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(changelog_prom_ex_prom_ex_status_info, kubernetes_namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The amount of time that has passed since the system has started.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "changelog_prom_ex_beam_stats_uptime_milliseconds_count{kubernetes_namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "stat",
   "description": "The amount of memory currently allocated by the BEAM.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "changelog_prom_ex_beam_memory_allocated_bytes{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Atom Count",
   "type": "stat",
   "description": "The number of atoms currently in the atom table.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "changelog_prom_ex_beam_stats_atom_count{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process Count",
   "type": "stat",
   "description": "The number of running BEAM processes currently running.",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "changelog_prom_ex_beam_stats_process_count{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port Count",
   "type": "stat",
   "description": "The number of currently active ports.",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "changelog_prom_ex_beam_stats_port_count{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ETS Table Count",
   "type": "stat",
   "description": "The number of currently allocated ETS tables.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "changelog_prom_ex_beam_stats_ets_count{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Stats on the current memory usage.",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(changelog_prom_ex_beam_memory_allocated_bytes{kubernetes_namespace=\"$namespace\"}) by(app, kubernetes_namespace)",
     "legendFormat": "Total Usage"
    },
    {
     "expr": "sum(changelog_prom_ex_beam_memory_atom_total_bytes{kubernetes_namespace=\"$namespace\"}) by(app, kubernetes_namespace)",
     "legendFormat": "Atoms"
    },
    {
     "expr": "sum(changelog_prom_ex_beam_memory_binary_total_bytes{kubernetes_namespace=\"$namespace\"}) by(app, kubernetes_namespace)",
     "legendFormat": "Binaries"
    },
    {
     "expr": "sum(changelog_prom_ex_beam_memory_code_total_bytes{kubernetes_namespace=\"$namespace\"}) by(app, kubernetes_namespace)",
     "legendFormat": "Code"
    },
    {
     "expr": "sum(changelog_prom_ex_beam_memory_ets_total_bytes{kubernetes_namespace=\"$namespace\"}) by(app, kubernetes_namespace)",
     "legendFormat": "ETS"
    },
    {
     "expr": "sum(changelog_prom_ex_beam_memory_processes_total_bytes{kubernetes_namespace=\"$namespace\"}) by(app, kubernetes_namespace)",
     "legendFormat": "Processes"
    }
   ]
  },
  {
   "title": "Port IO",
   "type": "graph",
   "description": "The number of bytes sent and received through ports.",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    {
     "format": "Bps",
     "label": "Data Received (-) / Data Sent (+)"
    }
   ],
   "targets": [
    {
     "expr": "sum(0 - irate(changelog_prom_ex_beam_stats_port_io_byte_count{kubernetes_namespace=\"$namespace\", type=\"input\"}[$__interval])) by(app, kubernetes_namespace)",
     "legendFormat": "Data Received"
    },
    {
     "expr": "sum(0 + irate(changelog_prom_ex_beam_stats_port_io_byte_count{kubernetes_namespace=\"$namespace\", type=\"output\"}[$__interval])) by(app, kubernetes_namespace)",
     "legendFormat": "Data Sent"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "graph",
   "description": "The number of garbage collection events that are occuring and the number of bytes reclaimed",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "locale", "label": "Garbage Collections" }
   ],
   "targets": [
    {
     "expr": "sum(irate(changelog_prom_ex_beam_stats_gc_count{kubernetes_namespace=\"$namespace\"}[$__interval])) by(app, kubernetes_namespace)",
     "legendFormat": "Garbage Collections"
    },
    {
     "expr": "sum(irate(changelog_prom_ex_beam_stats_gc_reclaimed_bytes{kubernetes_namespace=\"$namespace\"}[$__interval])) by(app, kubernetes_namespace)",
     "legendFormat": "Bytes Reclaimed"
    }
   ]
  },
  {
   "title": "VM Load",
   "type": "graph",
   "description": "The number of context switches that have occured along with the number of reductions.",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "locale", "label": "Reduction Count" }
   ],
   "targets": [
    {
     "expr": "sum(irate(changelog_prom_ex_beam_stats_reduction_count{kubernetes_namespace=\"$namespace\"}[$__interval])) by(app, kubernetes_namespace)",
     "legendFormat": "Reductions"
    },
    {
     "expr": "sum(irate(changelog_prom_ex_beam_stats_context_switch_count{kubernetes_namespace=\"$namespace\"}[$__interval])) by(app, kubernetes_namespace)",
     "legendFormat": "Context Switches"
    }
   ]
  },
  {
   "title": "Normal Scheduler Status",
   "type": "graph",
   "description": "Statistics regarding the normal scheduler.",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    {
     "format": "locale",
     "label": "Normal Run Queue (-) / Normal Tasks (+)"
    }
   ],
   "targets": [
    {
     "expr": "sum(irate(changelog_prom_ex_beam_stats_active_task_count{kubernetes_namespace=\"$namespace\", type=\"normal\"}[$__interval])) by(app, kubernetes_namespace)",
     "legendFormat": "Normal Tasks"
    },
    {
     "expr": "sum(0 - irate(changelog_prom_ex_beam_stats_run_queue_count{kubernetes_namespace=\"$namespace\", type=\"normal\"}[$__interval])) by(app, kubernetes_namespace)",
     "legendFormat": "Normal Run Queue"
    }
   ]
  },
  {
   "title": "Dirty Scheduler Status",
   "type": "graph",
   "description": "Statistics regarding the dirty schedulers.",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    {
     "format": "locale",
     "label": "Dirty Run Queue (-) / Dirty Tasks (+)"
    }
   ],
   "targets": [
    {
     "expr": "sum(irate(changelog_prom_ex_beam_stats_active_task_count{kubernetes_namespace=\"$namespace\", type=\"dirty\"}[$__interval])) by(app, kubernetes_namespace)",
     "legendFormat": "Dirty Tasks"
    },
    {
     "expr": "sum(0 - irate(changelog_prom_ex_beam_stats_run_queue_count{kubernetes_namespace=\"$namespace\", type=\"dirty\"}[$__interval])) by(app, kubernetes_namespace)",
     "legendFormat": "Dirty Run Queue"
    }
   ]
  },
  {
   "title": "Atom Table Size",
   "type": "graph",
   "description": "The number of atoms currently in the atom table",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale", "label": "Atoms" }
   ],
   "targets": [
    {
     "expr": "sum(changelog_prom_ex_beam_stats_atom_count{kubernetes_namespace=\"$namespace\"}) by(app, kubernetes_namespace)",
     "legendFormat": "Active ports"
    }
   ]
  },
  {
   "title": "Active Ports",
   "type": "graph",
   "description": "The number of active ports.",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "Ports" }
   ],
   "targets": [
    {
     "expr": "sum(changelog_prom_ex_beam_stats_port_count{kubernetes_namespace=\"$namespace\"}) by(app, kubernetes_namespace)",
     "legendFormat": "Active Ports"
    }
   ]
  },
  {
   "title": "Active BEAM Processes",
   "type": "graph",
   "description": "The number of running BEAM processes.",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "Processes" }
   ],
   "targets": [
    {
     "expr": "sum(changelog_prom_ex_beam_stats_process_count{kubernetes_namespace=\"$namespace\"}) by(app, kubernetes_namespace)",
     "legendFormat": "Active Processes"
    }
   ]
  },
  {
   "title": "ETS",
   "type": "graph",
   "description": "The number of active ETS tables.",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short", "label": "Tables" }
   ],
   "targets": [
    {
     "expr": "sum(changelog_prom_ex_beam_stats_ets_count{kubernetes_namespace=\"$namespace\"}) by(app, kubernetes_namespace)",
     "legendFormat": "Active ETS Tables"
    }
   ]
  },
  { "title": "System Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "OTP Major Version",
   "type": "stat",
   "description": "The OTP major version running the application.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changelog_prom_ex_beam_system_version_info{kubernetes_namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Word Size in Bytes",
   "type": "stat",
   "description": "The size of Erlang term words in bytes.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changelog_prom_ex_beam_system_word_size_bytes_info{kubernetes_namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Logical Processors",
   "type": "stat",
   "description": "The number of logical processors in the system.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changelog_prom_ex_beam_system_logical_processors_info{kubernetes_namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Logical Processors Available",
   "type": "stat",
   "description": "The number of logical processors available in the system.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changelog_prom_ex_beam_system_logical_processors_available_info{kubernetes_namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Logical Processors Online",
   "type": "stat",
   "description": "The number of logical processors online in the system.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changelog_prom_ex_beam_system_logical_processors_online_info{kubernetes_namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "OTP Compiler Options",
   "type": "table",
   "description": "Shows the various options that OTP was compiled with.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "{__name__=~\"changelog_prom_ex_beam_system_thread_support_info|changelog_prom_ex_beam_system_smp_support_info|changelog_prom_ex_beam_system_time_correction_support_info\", kubernetes_namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "System Limits",
   "type": "table",
   "description": "Shows information regarding the system limits of the BEAM instance.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 74 },
   "targets": [
    {
     "expr": "{__name__=~\"changelog_prom_ex_beam_system_ets_limit_info|changelog_prom_ex_beam_system_port_limit_info|changelog_prom_ex_beam_system_process_limit_info|changelog_prom_ex_beam_system_atom_limit_info\", kubernetes_namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Scheduler Information",
   "type": "table",
   "description": "Shows information regarding the schedulers configured for the BEAM instance.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 74 },
   "targets": [
    {
     "expr": "{__name__=~\"changelog_prom_ex_beam_system_dirty_cpu_schedulers_info|changelog_prom_ex_beam_system_dirty_cpu_schedulers_online_info|changelog_prom_ex_beam_system_dirty_io_schedulers_info|changelog_prom_ex_beam_system_schedulers_info|changelog_prom_ex_beam_system_schedulers_online_info\", kubernetes_namespace=\"$namespace\"}"
    }
   ]
  }
 ]
}