{
 "title": "PromEx - Phoenix - 2020.12.28",
 "description": "All the data that is presented here is captured by the PromEx Phoenix plugin (https://github.com/akoutmos/prom_ex/blob/master/lib/prom_ex/plugins/phoenix.ex)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(changelog_prom_ex_prom_ex_status_info, kubernetes_namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Apdex Score (Last 24h)",
   "type": "stat",
   "description": "The Apdex score of the app based on a satisfactory response time of 256ms and a tolerable response time of 1024ms. This only takes into account how long Phoenix has been handling the request and only requests that resulted in a 2xx status code. The score is based on the last 24 hours of requests.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (\n    sum(increase(changelog_prom_ex_phoenix_http_request_duration_milliseconds_bucket{kubernetes_namespace=\"$namespace\", le=\"256\", status=~\"2..\"}[24h])) + \n    (sum(increase(changelog_prom_ex_phoenix_http_request_duration_milliseconds_bucket{kubernetes_namespace=\"$namespace\", le=\"1024\", status=~\"2..\"}[24h])) - sum(increase(changelog_prom_ex_phoenix_http_request_duration_milliseconds_bucket{kubernetes_namespace=\"$namespace\", le=\"256\", status=~\"2..\"}[24h]))) / 2\n  ) \n  / \n  sum(increase(changelog_prom_ex_phoenix_http_request_duration_milliseconds_count{kubernetes_namespace=\"$namespace\", status=~\"2..\"}[24h]))\n) * 100"
    }
   ]
  },
  {
   "title": "Error Percentage (Last 24h)",
   "type": "stat",
   "description": "A percentage of responses that resulted in 400s or 500s over the past 24 hours.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(changelog_prom_ex_phoenix_http_requests_total{kubernetes_namespace=\"$namespace\", status=~\"4..|5..\"}[24h])) / sum(increase(changelog_prom_ex_phoenix_http_requests_total{kubernetes_namespace=\"$namespace\"}[24h]))"
    }
   ]
  },
  {
   "title": "Data Transferred (Last 24h)",
   "type": "stat",
   "description": "The amount of data transferred by Phoenix in a 24 hour rolling window.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(changelog_prom_ex_phoenix_http_response_size_bytes_sum{kubernetes_namespace=\"$namespace\"}[24h]))"
    }
   ]
  },
  {
   "title": "Total Requests Received (Last 24h)",
   "type": "stat",
   "description": "The amount of requests received by Phoenix in a 24 hour rolling window.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(changelog_prom_ex_phoenix_http_requests_total{kubernetes_namespace=\"$namespace\"}[24h]))"
    }
   ]
  },
  {
   "title": "Apdex Score (Last 1h)",
   "type": "stat",
   "description": "The Apdex score of the app based on a satisfactory response time of 256ms and a tolerable response time of 1024ms. This only takes into account how long Phoenix has been handling the request and only requests that resulted in a 2xx status code. The score is based on the previous hour of requests.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (\n    sum(increase(changelog_prom_ex_phoenix_http_request_duration_milliseconds_bucket{kubernetes_namespace=\"$namespace\", le=\"256\", status=~\"2..\"}[1h])) + \n    (sum(increase(changelog_prom_ex_phoenix_http_request_duration_milliseconds_bucket{kubernetes_namespace=\"$namespace\", le=\"1024\", status=~\"2..\"}[1h])) - sum(increase(changelog_prom_ex_phoenix_http_request_duration_milliseconds_bucket{kubernetes_namespace=\"$namespace\", le=\"256\", status=~\"2..\"}[1h]))) / 2\n  ) \n  / \n  sum(increase(changelog_prom_ex_phoenix_http_request_duration_milliseconds_count{kubernetes_namespace=\"$namespace\", status=~\"2..\"}[1h]))\n) * 100"
    }
   ]
  },
  {
   "title": "Error Percentage (Last 1h)",
   "type": "stat",
   "description": "A percentage of responses that resulted in 400s or 500s over the past hour.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(changelog_prom_ex_phoenix_http_requests_total{kubernetes_namespace=\"$namespace\", status=~\"4..|5..\"}[1h])) / sum(increase(changelog_prom_ex_phoenix_http_requests_total{kubernetes_namespace=\"$namespace\"}[1h]))"
    }
   ]
  },
  {
   "title": "Data Transferred (Last 1h)",
   "type": "stat",
   "description": "The amount of data transferred by Phoenix in the past hour.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(changelog_prom_ex_phoenix_http_response_size_bytes_sum{kubernetes_namespace=\"$namespace\"}[1h]))"
    }
   ]
  },
  {
   "title": "Total Requests Received (Last 1h)",
   "type": "stat",
   "description": "The amount of requests received by Phoenix in the past hour.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(changelog_prom_ex_phoenix_http_requests_total{kubernetes_namespace=\"$namespace\"}[1h]))"
    }
   ]
  },
  { "title": "HTTP Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Average HTTP Request Time",
   "type": "graph",
   "description": "The average request time per path per status code per HTTP method.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms", "label": "Response Time" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(irate(changelog_prom_ex_phoenix_http_request_duration_milliseconds_sum{kubernetes_namespace=\"$namespace\"}[$__interval])) by(path) / sum(irate(changelog_prom_ex_phoenix_http_request_duration_milliseconds_count{kubernetes_namespace=\"$namespace\"}[$__interval])) by(path))",
     "legendFormat": "{{ method }} {{ path }}"
    }
   ]
  },
  {
   "title": "Average HTTP Response Size",
   "type": "graph",
   "description": "The average response size per path per status code per HTTP method.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes", "label": "Response Size" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(irate(changelog_prom_ex_phoenix_http_response_size_bytes_sum{kubernetes_namespace=\"$namespace\"}[$__interval])) by(path) / sum(irate(changelog_prom_ex_phoenix_http_response_size_bytes_count{kubernetes_namespace=\"$namespace\"}[$__interval])) by(path))",
     "legendFormat": "{{ method }} {{ path }} :: {{ status }}"
    }
   ]
  },
  {
   "title": "Path Requests",
   "type": "graph",
   "description": "Shows the number of requests coming into certain paths and the resulting response codes.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "locale", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "topk(5, irate(changelog_prom_ex_phoenix_http_requests_total{kubernetes_namespace=\"$namespace\"}[$__interval]))",
     "legendFormat": "{{ method }} {{ path }} :: {{ status }}"
    }
   ]
  },
  {
   "title": "Response Status Codes",
   "type": "graph",
   "description": "The aggregate response status of all the requests.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "sum(irate(changelog_prom_ex_phoenix_http_requests_total{status=~\"2..\", kubernetes_namespace=\"$namespace\"}[$__interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(irate(changelog_prom_ex_phoenix_http_requests_total{status=~\"4..\", kubernetes_namespace=\"$namespace\"}[$__interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(irate(changelog_prom_ex_phoenix_http_requests_total{status=~\"5..\", kubernetes_namespace=\"$namespace\"}[$__interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "heatmap",
   "description": "A heatmap showing the request time spread across all requests (regardless of path).",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(irate(changelog_prom_ex_phoenix_http_request_duration_milliseconds_bucket{kubernetes_namespace=\"$namespace\"}[$__interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Response Payload Size",
   "type": "heatmap",
   "description": "A heatmap showing the response payload size spread across all requests (regardless of path).",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "sum(irate(changelog_prom_ex_phoenix_http_response_size_bytes_bucket{kubernetes_namespace=\"$namespace\"}[$__interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Channel Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Channel Join Events",
     "type": "graph",
     "description": "How many channel joins have occurred over time.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short", "label": "Channel joins" }
     ],
     "targets": [
      {
       "expr": "irate(changelog_prom_ex_phoenix_channel_joined_total{kubernetes_namespace=\"$namespace\"}[$__interval])",
       "legendFormat": "{{ transport }} :: {{ result }}"
      }
     ]
    },
    {
     "title": "Channel Message Handle Time",
     "type": "heatmap",
     "description": "A heatmap showing the request time spread across all channel events.",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 58 },
     "targets": [
      {
       "expr": "sum(irate(changelog_prom_ex_phoenix_channel_handled_in_duration_milliseconds_bucket{kubernetes_namespace=\"$namespace\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Average Channel Response Time",
     "type": "graph",
     "description": "The average response time for a channel message.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "ms", "label": "Response Time" }
     ],
     "targets": [
      {
       "expr": "sum(irate(changelog_prom_ex_phoenix_channel_handled_in_duration_milliseconds_sum{kubernetes_namespace=\"$namespace\"}[$__interval])) by(path) / sum(irate(changelog_prom_ex_phoenix_channel_handled_in_duration_milliseconds_count{kubernetes_namespace=\"$namespace\"}[$__interval])) by(path)"
      }
     ]
    }
   ]
  }
 ]
}