# https://github.com/parca-dev/parca-agent/pull/132
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/version: v0.2.0-45-gdfa59a1
    spec:
      containers:
        - name: parca-agent
          image: ghcr.io/parca-dev/parca-agent:v0.2.0-45-gdfa59a1
