spec:
  template:
    spec:
      containers:
        - name: parca
          resources:
            requests:
              cpu: 2
              memory: 4Gi
            limits:
              cpu: 2
              memory: 4Gi
