#!/usr/bin/env bash
#MISE description="Make production deployment resilient to a single region failure"
set -euo pipefail
[ -z "${DEBUG:-}" ] || set -x
source "${MISE_PROJECT_ROOT}/mise-tasks/team/_lib.sh"

require_env APP_PROD_INSTANCE

echo "Why do we need this? 🤔 https://status.changelog.com/incident/513790"
cd "fly.io/${APP_PROD_INSTANCE}"
flyctl scale count 2 --max-per-region 1 --region iad,ewr
