#!/usr/bin/env bash
#MISE description="Stop Postgres server"
set -euo pipefail

if ! command -v docker &>/dev/null; then
    echo "Docker is not installed."
    exit 127
fi

if docker compose ps db --status running --quiet 2>/dev/null | grep -q .; then
    docker compose down db
else
    echo "Postgres is not running"
fi
