#!/bin/bash -ex

# swap lines 4 and 5 if you want to download the episodes
# for type in founderstalk  gotime  jsparty  podcast  rfc  spotlight practicalai afk; do
for type in icons avatars covers logos news_ads news_items; do
  rsync --recursive \
        --partial \
        --progress \
        --ignore-existing \
        cl-app:/data/www/uploads/$type \
        priv/uploads/
done
