#!/bin/bash -ex

brew install markdown

# convert with markdown tool
git clone --depth 1 https://github.com/thechangelog/legal && \
cd legal && \
markdown privacy.md > ../../web/templates/page/privacy.html.eex && \
markdown terms.md > ../../web/templates/page/terms.html.eex 

# clean up
rm -rf ./legal/

# Next Step adjust the static page when needed