#!/bin/bash -ex

psql changelog_dev <<EOF
update news_items set impression_count=0, click_count=0;
update news_ads set impression_count=0, click_count=0;
update news_sponsorships set impression_count=0, click_count=0;

update people set email = ((select floor(random() * 10000000) + 1 where people.id = people.id) || '@fake.com');
update people set joined_at=NULL, signed_in_at=NULL, auth_token=NULL, auth_token_expires_at=NULL, slack_id=NULL;

update episodes set import_count=0, download_count=0, reach_count=0, doc_url=NULL;
update podcasts set download_count=0, reach_count=0, subscribers=NULL;

delete from oban_jobs;
delete from episode_stats;

delete from posts where published='false';
EOF
