# Inspired by https://github.com/fly-apps/live_beats/blob/master/fly.toml
# Full app config reference: https://fly.io/docs/reference/configuration/
app = "changelog-2022-03-13"

kill_signal = "SIGTERM"
kill_timeout = 5

[build]
image = "thechangelog/changelog.com:master"

[deploy]
strategy = "bluegreen"

[env]
AWS_ASSETS_BUCKET = "changelog-assets"
AWS_REGION = "us-east-1"
AWS_UPLOADS_HOST = "https://changelog-assets.s3.amazonaws.com"
PORT = "4000"
STATIC_URL_HOST = "cdn.changelog.com"
URL_HOST = "changelog.com"

[[services]]
internal_port = 4000
processes = ["app"]
protocol = "tcp"

[[services.http_checks]]
grace_period = "120s"
interval = 15000
method = "get"
path = "/health"
protocol = "http"
timeout = 10000

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.ports]]
handlers = ["http"]
port = "80"
force_https = true

# Increase the limit of connections that a single app instance can handle
# Otherwise Fly proxy will start sending the requests to instances that we don't have... yet
# Related to https://github.com/thechangelog/changelog.com/issues/424
[services.concurrency]
hard_limit = 2500
soft_limit = 2000
type = "connections"
