#!/usr/bin/env bash
#MISE description="Build the runtime image, then test and build the prod image"
#MISE raw=true
set -euo pipefail
[ -z "${DEBUG:-}" ] || set -x

mise run docker:build-runtime

mise run docker:test ::: docker:build-prod
