#!/usr/bin/env bash
#MISE description="Delete & replace changelog_dev with a prod db dump"
#MISE depends=["postgres:up"]
#USAGE flag "-f --format <format>" help="Dump format" default="c"
set -euo pipefail

FORMAT="${usage_format:-c}"
CHANGELOG_DEV_DB="${CHANGELOG_DEV_DB:?must be set}"
DB_PROD_HOST="${DB_PROD_HOST:?must be set}"
DB_PROD_USERNAME="${DB_PROD_USERNAME:?must be set}"
DB_PROD_DBNAME="${DB_PROD_DBNAME:?must be set}"

echo ""
read -rp "This DELETES and REPLACES ${CHANGELOG_DEV_DB} with the prod db dump. Continue? [y/N] " confirm
if [[ "${confirm}" != "y" && "${confirm}" != "Y" ]]; then
    echo "Aborted."
    exit 0
fi

echo -e "\n🛬 Dumping prod db..."
if [[ ! -f "${DB_PROD_DBNAME}.${FORMAT}.sql" ]]; then
    time PGSSLMODE=require PGPASSWORD="$(op read op://changelog/neon/password)" pg_dump \
        --format="${FORMAT}" --verbose \
        --host="${DB_PROD_HOST}" \
        --username="${DB_PROD_USERNAME}" \
        --dbname="${DB_PROD_DBNAME}" > "${DB_PROD_DBNAME}.${FORMAT}.sql"
fi

echo -e "\n🛫 Recreating ${CHANGELOG_DEV_DB} from prod dump..."
dropdb "${CHANGELOG_DEV_DB}"
createdb "${CHANGELOG_DEV_DB}"
time pg_restore \
    --format="${FORMAT}" --verbose \
    --dbname="${CHANGELOG_DEV_DB}" \
    --exit-on-error \
    --no-owner \
    --no-privileges < "${DB_PROD_DBNAME}.${FORMAT}.sql"

echo -e "\n⚡️ Warm up the query planner..."
time psql --dbname="${CHANGELOG_DEV_DB}" --command "ANALYZE VERBOSE;"
