# https://fly.io/docs/reference/configuration/

app = "dagger-engine-2024-03-28"
primary_region = "ord"

kill_signal = "SIGINT"
kill_timeout = 30

[build]
  image = "registry.dagger.io/engine:v0.10.3"

[mounts]
  source = "dagger_engine_2024_03_28"
  destination = "/var/lib/dagger"

[processes]
  dagger = "--addr unix:///var/run/buildkit/buildkitd.sock --addr tcp://0.0.0.0:8080"

[checks]
  [checks.grpc]
    grace_period = "3s"
    interval = "2s"
    port = 8080
    timeout = "1s"
    type = "tcp"
