#!/usr/bin/env bash
#MISE description="Create a new branch off the prod db"
set -euo pipefail

NEON_PROJECT_ID="${NEON_PROJECT_ID:?must be set}"
NEON_DB_BRANCH="${USER}-$(date +%Y-%m-%d)"

echo -e "\n🔒 Checking Neon auth..."
neonctl projects get "${NEON_PROJECT_ID}" || neonctl auth

echo -e "\n🌲 Creating Neon prod db branch..."
neonctl branches get --project-id="${NEON_PROJECT_ID}" "${NEON_DB_BRANCH}" \
    || neonctl branches create --project-id="${NEON_PROJECT_ID}" --name="${NEON_DB_BRANCH}"

CONN_STRING=$(neonctl connection-string "${NEON_DB_BRANCH}" \
    --project-id="${NEON_PROJECT_ID}" \
    --role-name="${DB_PROD_USERNAME}" \
    --database-name="${DB_PROD_DBNAME}" \
    --extended --output=yaml \
    | awk '/connection_string:/ { print $2 }')

echo -e "\n⚡️ Warm up the query planner..."
time psql "${CONN_STRING}" --command "ANALYZE VERBOSE;"

echo -e "\n💡 To use this Neon db branch with your local dev app, run:"
echo "   mise run dev-with-neon-branch ${NEON_DB_BRANCH}"
