name: "Dagger on K8s"

on:
  workflow_call:

jobs:
  run:
    runs-on: dagger-06x
    continue-on-error: true
    steps:
      - name: "Checkout code..."
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache-dependency-path: "magefiles/go.sum"

      - name: "Build, test & publish..."
        env:
          IMAGE_OWNER: "${{ vars.IMAGE_OWNER }}"
          GHCR_USERNAME: "${{ github.actor }}"
          GHCR_PASSWORD: "${{ secrets.GHCR_PASSWORD }}"
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          R2_API_HOST: "${{ secrets.R2_API_HOST }}"
          R2_ACCESS_KEY_ID: "${{ secrets.R2_ACCESS_KEY_ID }}"
          R2_SECRET_ACCESS_KEY: "${{ secrets.R2_SECRET_ACCESS_KEY }}"
          R2_ASSETS_BUCKET: "${{ env.R2_ASSETS_BUCKET }}"
          OBAN_KEY_FINGERPRINT: "${{ secrets.OBAN_KEY_FINGERPRINT }}"
          OBAN_LICENSE_KEY: "${{ secrets.OBAN_LICENSE_KEY }}"
        run: |
          cd magefiles
          go run main.go -w ../ ci

      # TODO: run this in Dagger
      # https://github.com/rtCamp/action-slack-notify/blob/v2.2.0/main.go
      # - name: "Announce deploy in #dev Slack..."
