name: "Dagger on GitHub"

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code..."
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
          cache-dependency-path: "magefiles/go.sum"

      - name: "Build, test & publish..."
        env:
          IMAGE_OWNER: "${{ vars.IMAGE_OWNER }}"
          GHCR_USERNAME: "${{ github.actor }}"
          GHCR_PASSWORD: "${{ secrets.GHCR_PASSWORD }}"
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          R2_API_HOST: "${{ secrets.R2_API_HOST }}"
          R2_ACCESS_KEY_ID: "${{ secrets.R2_ACCESS_KEY_ID }}"
          R2_SECRET_ACCESS_KEY: "${{ secrets.R2_SECRET_ACCESS_KEY }}"
          R2_ASSETS_BUCKET: "${{ env.R2_ASSETS_BUCKET }}"
          OBAN_KEY_FINGERPRINT: "${{ secrets.OBAN_KEY_FINGERPRINT }}"
          OBAN_LICENSE_KEY: "${{ secrets.OBAN_LICENSE_KEY }}"
        run: |
          cd magefiles
          go run main.go -w ../ ci

      - name: "Deploy..."
        if: ${{ github.repository == 'thechangelog/changelog.com' && github.ref_name == 'master' }}
        env:
          IMAGE_OWNER: "${{ vars.IMAGE_OWNER }}"
          GHCR_USERNAME: "${{ github.actor }}"
          GHCR_PASSWORD: "${{ secrets.GHCR_PASSWORD }}"
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          R2_API_HOST: "${{ secrets.R2_API_HOST }}"
          R2_ACCESS_KEY_ID: "${{ secrets.R2_ACCESS_KEY_ID }}"
          R2_SECRET_ACCESS_KEY: "${{ secrets.R2_SECRET_ACCESS_KEY }}"
          R2_ASSETS_BUCKET: "${{ env.R2_ASSETS_BUCKET }}"
          OBAN_KEY_FINGERPRINT: "${{ secrets.OBAN_KEY_FINGERPRINT }}"
          OBAN_LICENSE_KEY: "${{ secrets.OBAN_LICENSE_KEY }}"
        run: |
          cd magefiles
          go run main.go -w ../ cd

      - name: "Announce deploy in #kaizen Zulip..."
        if: ${{ github.repository == 'thechangelog/changelog.com' && github.ref_name == 'master' }}
        uses: zulip/github-actions-zulip/send-message@v1
        with:
          api-key: ${{ secrets.ZULIP_BOT_API_KEY }}
          email: "logbot-bot@changelog.zulipchat.com"
          organization-url: "https://changelog.zulipchat.com"
          to: "kaizen"
          type: "stream"
          topic: "Code deploys"
          content: |
            ${{ github.actor }} just successfully deployed [${{ env.SHORT_SHA }}](https://github.com/thechangelog/changelog.com/commit/${{ github.sha }}):

            > ${{ github.event.commits[0].message }}
