name: "Dagger on GitHub"

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code..."
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache-dependency-path: "magefiles/go.sum"

      - name: "Build, test, publish & deploy..."
        env:
          IMAGE_OWNER: "${{ vars.IMAGE_OWNER }}"
          GHCR_USERNAME: "${{ github.actor }}"
          GHCR_PASSWORD: "${{ secrets.GHCR_PASSWORD }}"
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        run: |
          cd magefiles
          go run main.go -w ../ ci cd

      - name: "Announce deploy in #dev Slack..."
        if: ${{ github.repository == 'thechangelog/changelog.com' && github.ref_name == 'master' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          MSG_MINIMAL: "commit,actions url"
          SLACK_CHANNEL: dev
          SLACK_USERNAME: "GitHub Actions"
          SLACK_FOOTER: "Just got shipped to https://changelog.com"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
