name: "Dagger on K8s"

on:
  workflow_call:

jobs:
  run:
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: "Checkout code..."
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache-dependency-path: "magefiles/go.sum"

      - name: "Build, test, publish & deploy..."
        env:
          IMAGE_OWNER: "${{ vars.IMAGE_OWNER }}"
          GHCR_USERNAME: "${{ github.actor }}"
          GHCR_PASSWORD: "${{ secrets.GHCR_PASSWORD }}"
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        run: |
          cd magefiles
          go run main.go -w ../ ci

      # TODO: run this in Dagger
      # - name: "Announce deploy in #dev Slack..."
